### ISSUE TITLE
Collection contains single image but export to PPT and PDF contains 2 images

### ISSUE THREAD

**Issue by amrri06** [curationexperts/trove#209] opened 2014-11-05 21:43 UTC
I opened up a collection called Mike's colleciton.  It contained a sindle image.  I chose the export to ppt option under actions.  I expected download presentation slides containing the collection title, 1 metadata slide and 1 image slide.  the slides contained the collection title and 2 image and 2 metadata slides. I got the same behavior when I downloaded the pdf.  I'll send the pdf and ppt in an email to alcicia cozine and mark.

**Comment by mark-dce** [comment] 2015-01-08 20:00
Are the two image slides of the same image or of different images.

**Comment by acozine** [comment] 2015-01-15 19:37
Unable to reproduce. Closing for now; if the behavior recurs, we can open a new ticket.

**Closed by acozine** 2015-01-15 19:37 UTC
