### ISSUE TITLE
Nested collection disappearing in Facet display

### ISSUE THREAD

**Issue by amrri06** [curationexperts/trove#206] opened 2014-11-04 16:54 UTC
New course collection was created called: "Basilica Plans".  Images were successfully added to this folder.  After adding the images, "Basilica Plans" was moved to become a nested collection under the "Basilicas" course collection.  It appeared to work fine, but shortly after, "Basilica Plans" (uc:77) folder disappeared from the "Basilicas" Course Collections hierarchy, but the folder could be found via search.  When found via search it was displayed as an individual collection, not a subcollection to "Basilicas." When clicking on the folder for "Basilica Plans" a server error occurs when
and the "We're sorry, but something went wrong" error message is displayed.

We were not able to reproduce this issue.

**Comment by acozine** [comment] 2015-01-15 19:33
Unable to reproduce. Closing ticket - if the problem recurs, we can open a new ticket.

**Closed by acozine** 2015-01-15 19:33 UTC
